# Generated by Django 5.1.6 on 2025-03-31 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='category',
            field=models.CharField(choices=[('cafe', 'Кафе'), ('restaurant', 'Ресторан'), ('other', 'Другое')], default='other', max_length=20),
        ),
    ]
